FROM php:7.4-fpm

# Copy composer.lock and composer.json
COPY ./composer.lock* ./composer.json* /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
build-essential \
libpng-dev \
libjpeg62-turbo-dev \
libfreetype6-dev \
libonig-dev \
libzip-dev \
libmcrypt-dev \
zlib1g-dev \
libxml2-dev \
graphviz \
locales \
zip \
jpegoptim optipng pngquant gifsicle \
unzip \
curl

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo pdo_mysql mbstring bcmath zip exif pcntl sockets
RUN docker-php-ext-install gd
RUN pecl install -o -f redis \
&&  rm -rf /tmp/pear \
&&  docker-php-ext-enable redis

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Will uese the script to wait untill the application be up so we can run
# composer install or Db migration commands: https://github.com/vishnubob/wait-for-it
COPY wait-for-it.sh /usr/bin/wait-for-it
RUN chmod +x /usr/bin/wait-for-it

# Copy existing application directory contents
COPY . /var/www

# laravel settings
RUN chown -R www-data:www-data /var/www
RUN chmod -R 755 . /var/www

# Expose port 9000 and start php-fpm server
EXPOSE 9000

#install laravel dependencies then run the app
CMD composer install; wait-for-it mysql:3306 -- php artisan migrate; php-fpm;
