FROM node:12-alpine

COPY ./package.json /usr/service/package.json
COPY ./yarn.lock /usr/service/yarn.lock

WORKDIR /usr/service

RUN yarn

COPY . /usr/service

ENV DOCKERIZE_VERSION v0.6.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

EXPOSE 8585
CMD dockerize -wait tcp://amqp:5672 -timeout 60m yarn run start:dev
