apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chat-engine.fullname" . }}
  labels:
    {{- include "chat-engine.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chat-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chat-engine.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chat-engine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /socket.io
          #     port: 3000
          # readinessProbe:
          #   httpGet:
          #     path: /socket.io
          #     port: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: STATEFULSET_HOST
            value: {{ .Values.STATEFULSET_HOST | quote }}
          - name: NODE_ENV
            value: {{ .Values.NODE_ENV | quote }}
          - name: SOCKET_IO_PORT
            value: {{ .Values.SOCKET_IO_PORT | quote }}
          - name: RABBITMQ_DEFAULT_USER
            value: {{ .Values.RABBITMQ_DEFAULT_USER | quote }}
          - name: RABBITMQ_DEFAULT_PASS
            value: {{ .Values.RABBITMQ_DEFAULT_PASS | quote }}
          - name: RABBITMQ_URI
            value: {{ .Values.RABBITMQ_URI | quote }}
      terminationGracePeriodSeconds: 120
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
